### ISSUE TITLE
Mehrere Möbel aufeinmal kaufen

### ISSUE THREAD

**Issue by Leonidas1337xx** [Wielandini/playhabbo#7]
Nur 1 Möbel pro kauf möglich, Funktion mehrere aufeinmal zu kaufen fehlt

**Comment by Wielandini** [comment]
![image](https://user-images.githubusercontent.com/70216141/108573057-02e47980-7314-11eb-9e03-bff609e5a4e5.png)
Menge ist Auswählbar und kann man eingeben
